// Copyright (c) 2025 Pedro Botelho
// All rights reserved

#ifndef BUZZER_H
#define BUZZER_H

#include "timer.h"
#include "gpio.h"

#define BUZZER_TIMER_PS     (1024)

#define NO_NOTE  0

#define NOTE_C2     (TMR_CALC_HZ(65, BUZZER_TIMER_PS))
#define NOTE_CS2    (TMR_CALC_HZ(69, BUZZER_TIMER_PS))
#define NOTE_D2     (TMR_CALC_HZ(73, BUZZER_TIMER_PS))
#define NOTE_DS2    (TMR_CALC_HZ(78, BUZZER_TIMER_PS))
#define NOTE_E2     (TMR_CALC_HZ(82, BUZZER_TIMER_PS))
#define NOTE_F2     (TMR_CALC_HZ(87, BUZZER_TIMER_PS))
#define NOTE_FS2    (TMR_CALC_HZ(93, BUZZER_TIMER_PS))
#define NOTE_G2     (TMR_CALC_HZ(98, BUZZER_TIMER_PS))
#define NOTE_GS2    (TMR_CALC_HZ(104, BUZZER_TIMER_PS))
#define NOTE_A2     (TMR_CALC_HZ(110, BUZZER_TIMER_PS))
#define NOTE_AS2    (TMR_CALC_HZ(117, BUZZER_TIMER_PS))
#define NOTE_B2     (TMR_CALC_HZ(123, BUZZER_TIMER_PS))
#define NOTE_C3     (TMR_CALC_HZ(131, BUZZER_TIMER_PS))
#define NOTE_CS3    (TMR_CALC_HZ(139, BUZZER_TIMER_PS))
#define NOTE_D3     (TMR_CALC_HZ(147, BUZZER_TIMER_PS)) 
#define NOTE_DS3    (TMR_CALC_HZ(156, BUZZER_TIMER_PS)) 
#define NOTE_E3     (TMR_CALC_HZ(165, BUZZER_TIMER_PS)) 
#define NOTE_F3     (TMR_CALC_HZ(175, BUZZER_TIMER_PS)) 
#define NOTE_FS3    (TMR_CALC_HZ(185, BUZZER_TIMER_PS)) 
#define NOTE_G3     (TMR_CALC_HZ(196, BUZZER_TIMER_PS)) 
#define NOTE_GS3    (TMR_CALC_HZ(208, BUZZER_TIMER_PS)) 
#define NOTE_A3     (TMR_CALC_HZ(220, BUZZER_TIMER_PS)) 
#define NOTE_AS3    (TMR_CALC_HZ(233, BUZZER_TIMER_PS)) 
#define NOTE_B3     (TMR_CALC_HZ(247, BUZZER_TIMER_PS)) 
#define NOTE_C4     (TMR_CALC_HZ(262, BUZZER_TIMER_PS)) 
#define NOTE_CS4    (TMR_CALC_HZ(277, BUZZER_TIMER_PS)) 
#define NOTE_D4     (TMR_CALC_HZ(294, BUZZER_TIMER_PS)) 
#define NOTE_DS4    (TMR_CALC_HZ(311, BUZZER_TIMER_PS)) 
#define NOTE_E4     (TMR_CALC_HZ(330, BUZZER_TIMER_PS)) 
#define NOTE_F4     (TMR_CALC_HZ(349, BUZZER_TIMER_PS)) 
#define NOTE_FS4    (TMR_CALC_HZ(370, BUZZER_TIMER_PS)) 
#define NOTE_G4     (TMR_CALC_HZ(392, BUZZER_TIMER_PS)) 
#define NOTE_GS4    (TMR_CALC_HZ(415, BUZZER_TIMER_PS)) 
#define NOTE_A4     (TMR_CALC_HZ(440, BUZZER_TIMER_PS)) 
#define NOTE_AS4    (TMR_CALC_HZ(466, BUZZER_TIMER_PS)) 
#define NOTE_B4     (TMR_CALC_HZ(494, BUZZER_TIMER_PS)) 
#define NOTE_C5     (TMR_CALC_HZ(523, BUZZER_TIMER_PS)) 
#define NOTE_CS5    (TMR_CALC_HZ(554, BUZZER_TIMER_PS)) 
#define NOTE_D5     (TMR_CALC_HZ(587, BUZZER_TIMER_PS)) 
#define NOTE_DS5    (TMR_CALC_HZ(622, BUZZER_TIMER_PS)) 
#define NOTE_E5     (TMR_CALC_HZ(659, BUZZER_TIMER_PS)) 
#define NOTE_F5     (TMR_CALC_HZ(698, BUZZER_TIMER_PS)) 
#define NOTE_FS5    (TMR_CALC_HZ(740, BUZZER_TIMER_PS)) 
#define NOTE_G5     (TMR_CALC_HZ(784, BUZZER_TIMER_PS)) 
#define NOTE_GS5    (TMR_CALC_HZ(831, BUZZER_TIMER_PS)) 
#define NOTE_A5     (TMR_CALC_HZ(880, BUZZER_TIMER_PS)) 
#define NOTE_AS5    (TMR_CALC_HZ(932, BUZZER_TIMER_PS)) 
#define NOTE_B5     (TMR_CALC_HZ(988, BUZZER_TIMER_PS)) 
#define NOTE_C6     (TMR_CALC_HZ(1047, BUZZER_TIMER_PS)) 
#define NOTE_CS6    (TMR_CALC_HZ(1109, BUZZER_TIMER_PS)) 
#define NOTE_D6     (TMR_CALC_HZ(1175, BUZZER_TIMER_PS)) 
#define NOTE_DS6    (TMR_CALC_HZ(1245, BUZZER_TIMER_PS)) 
#define NOTE_E6     (TMR_CALC_HZ(1319, BUZZER_TIMER_PS)) 
#define NOTE_F6     (TMR_CALC_HZ(1397, BUZZER_TIMER_PS)) 
#define NOTE_FS6    (TMR_CALC_HZ(1480, BUZZER_TIMER_PS)) 
#define NOTE_G6     (TMR_CALC_HZ(1568, BUZZER_TIMER_PS)) 
#define NOTE_GS6    (TMR_CALC_HZ(1661, BUZZER_TIMER_PS)) 
#define NOTE_A6     (TMR_CALC_HZ(1760, BUZZER_TIMER_PS)) 
#define NOTE_AS6    (TMR_CALC_HZ(1865, BUZZER_TIMER_PS)) 
#define NOTE_B6     (TMR_CALC_HZ(1976, BUZZER_TIMER_PS)) 
#define NOTE_C7     (TMR_CALC_HZ(2093, BUZZER_TIMER_PS)) 
#define NOTE_CS7    (TMR_CALC_HZ(2217, BUZZER_TIMER_PS)) 
#define NOTE_D7     (TMR_CALC_HZ(2349, BUZZER_TIMER_PS)) 
#define NOTE_DS7    (TMR_CALC_HZ(2489, BUZZER_TIMER_PS)) 
#define NOTE_E7     (TMR_CALC_HZ(2637, BUZZER_TIMER_PS)) 
#define NOTE_F7     (TMR_CALC_HZ(2794, BUZZER_TIMER_PS)) 
#define NOTE_FS7    (TMR_CALC_HZ(2960, BUZZER_TIMER_PS)) 
#define NOTE_G7     (TMR_CALC_HZ(3136, BUZZER_TIMER_PS)) 
#define NOTE_GS7    (TMR_CALC_HZ(3322, BUZZER_TIMER_PS)) 
#define NOTE_A7     (TMR_CALC_HZ(3520, BUZZER_TIMER_PS)) 
#define NOTE_AS7    (TMR_CALC_HZ(3729, BUZZER_TIMER_PS)) 
#define NOTE_B7     (TMR_CALC_HZ(3951, BUZZER_TIMER_PS)) 
#define NOTE_C8     (TMR_CALC_HZ(4186, BUZZER_TIMER_PS)) 
#define NOTE_CS8    (TMR_CALC_HZ(4435, BUZZER_TIMER_PS)) 
#define NOTE_D8     (TMR_CALC_HZ(4699, BUZZER_TIMER_PS)) 
#define NOTE_DS8    (TMR_CALC_HZ(4978, BUZZER_TIMER_PS)) 

typedef struct buzzer_t {
    timer_id id;
    timer_compare_channel channel;
    gpio_t gpio;
} buzzer_t;

void buzzer_init(const buzzer_t* buzzer);

void buzzer_tone(const buzzer_t* buzzer, uint16_t tone);

void buzzer_no_tone(const buzzer_t* buzzer);

#endif // BUZZER_H
